application: marmalade-words
version: 1
runtime: php
threadsafe: true
api_version: 1

handlers:
- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /fonts
  static_dir: public/fonts

- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico

- url: /.*
  script: public/web.php
