<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Vocal Training</title>

    <script type="text/javascript"
            src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js">
    </script>

    <link type="text/css" rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.css">
</head>
<body>
<ul>
    <li><a href="phrases">Phrases</a></li>
    <li><a href="words">Words</a></li>
    <li><a href="https://number-pitch.appspot.com">Number Pitch</a></li>
</ul>
</body>
</html>