<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Vocal Training</title>

    <script type="text/javascript"
            src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js">
    </script>
    <script src="js/main.js" async="async"></script>
    <link type="text/css" rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.css">
    <link type="text/css" rel="stylesheet" href="css/fonts.css">
    <link type="text/css" rel="stylesheet" href="css/main.css">
</head>
<body class="<?php echo $this->app->escape($this->config->getType()) ?>"
      data-interval="<?php echo $this->app->escape($this->config->getInterval()) ?>"
      data-reminder="<?php echo $this->app->escape($this->config->getReminder()) ?>">
<?php echo $this->app->escape(strtoupper($this->randomLines->getLine())); ?>
</body>
</html>